version: '3'
services:
  vsnry-client-app:
    build: 
      context: ./vsnry-client
      dockerfile: Dockerfile.dev
    container_name: vsnry-client-app
    ports:
      - 3000:3000
    volumes:
      - ./vsnry-client/src:/app/src
  vsnry-admin-app:
    build:
      context: ./vsnry-admin
      dockerfile: Dockerfile.dev
    container_name: vsnry-admin-app
    ports:
      - 5000:3000
    volumes:
      - ./vsnry-admin/src:/app/src