# lucian@web.de
### 63f4c2720e8a298d3c21be6c
### Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjg5MjQxMTY5fQ.WNBDqUO7nJ_dSgDkjgT5UMObJF8CO2j4CzaYf3r62QQ

# adrian@web.de
### 640606b7719c50752e37dc96
### Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRyaWFuIiwiZW1haWwiOiJhZHJpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjQwNjA2Yjc3MTljNTA3NTJlMzdkYzk2IiwiaWF0IjoxNjg5MzI3NTY5fQ.FWq_z2su4SA6ooIcdwffjsucgivudHLU_pLRnxuK_RQ


# ---------------------------------------------------------------
### LOGIN 
# ---------------------------------------------------------------

POST http://localhost:1337/users/login
Content-Type: application/json

{
    "credentials": {
        "email": "lucian@web.de",
        "password": "Password#123"
    }
}

###

POST http://localhost:1337/users/login
Content-Type: application/json

{
    "credentials": {
        "email": "adrian@web.de",
        "password": "Password#123"
    }
}

###

POST http://localhost:1337/users/login
Content-Type: application/json

{
    "credentials": {
        "email": "pop@web.de",
        "password": "Password#123"
    }
}

# ---------------------------------------------------------------
### AUTH CONFIRM 
# ---------------------------------------------------------------

POST http://localhost:1337/auth-confirm
Content-Type: application/json

{
    "name": "Lucian",
    "email": "lucian@web.de",
    "userId": "63f4c2720e8a298d3c21be6c",
    "authCode": "B739BA"
}

###

POST http://localhost:1337/auth-confirm
Content-Type: application/json

{
    "name": "Adrian",
    "email": "adrian@web.de",
    "userId": "640606b7719c50752e37dc96",
    "authCode": "F05429"
}

###

POST http://localhost:1337/auth-confirm
Content-Type: application/json

{
    "name": "Pop",
    "email": "pop@web.de",
    "userId": "64afb1b8a6089171b842b31c",
    "authCode": "4C051C"
}

# ---------------------------------------------------------------
### FORGOT PASSWORD 
# ---------------------------------------------------------------

POST http://localhost:1337/forgot-password/request
Content-Type: application/json

{
    "email": "lucian@web.de"
}

###

PATCH http://localhost:1337/forgot-password/reset
Content-Type: application/json

{
    "password": "Password#1234",
    "userId": "63f4c2720e8a298d3c21be6c",
    "token": "ad071d354c0640665847001c9617aaacb5f195c3b8ac36ec7f5d40171a1d6524"
}

# ---------------------------------------------------------------
### UPDATE CREDENTIALS
# ---------------------------------------------------------------

### --- NAME --- ###

PATCH  http://localhost:1337/api/update-credentials/name?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjc4MTIxMDQxfQ.Wu48R418rz2ocPP0L83sA-x3m7WKQqlI8AsfRA1Fzdg

{
    "name": "Lucian"
}

### --- EMAIL --- ###

POST  http://localhost:1337/api/update-credentials/email-update-request?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjc4MTIxMDQxfQ.Wu48R418rz2ocPP0L83sA-x3m7WKQqlI8AsfRA1Fzdg

{
    "newEmail": "luciano@web.de"
}

###

PATCH  http://localhost:1337/update-credentials/email-update-reset
Content-Type: application/json

{
    "userId": "63f4c2720e8a298d3c21be6c",
    "token": "ef75ea5d345bf64ddffbc7b9abbd416f4c10db1373584279a56dde4032e59f09"
}

### --- PASSWORD --- ###

PATCH  http://localhost:1337/api/update-credentials/password?userId=64afb1b8a6089171b842b31c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUG9wIiwiZW1haWwiOiJwb3BhQHdlYi5kZSIsInVzZXJJZCI6IjY0YWZiMWI4YTYwODkxNzFiODQyYjMxYyIsImlhdCI6MTY4OTIzOTIxNX0.ziwsTAVRcMv6E29W3Dc5U9yjiOARIhexAxuinuwByfY

{
    "currentPassword": "Password123#",
    "newPassword": "Password#123"
}

# ---------------------------------------------------------------
### ADD NEW ADMIN 
# ---------------------------------------------------------------

POST http://localhost:1337/api/add-admin/request?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjg5MjQxMTY5fQ.WNBDqUO7nJ_dSgDkjgT5UMObJF8CO2j4CzaYf3r62QQ

{
    "newAdminEmail": "popadrian@web.de"
}

###

POST http://localhost:1337/api/add-admin/confirm?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjg5MjQxMTY5fQ.WNBDqUO7nJ_dSgDkjgT5UMObJF8CO2j4CzaYf3r62QQ

{
    "authCode": "997D62",
    "newAdminEmail": "popadrian@web.de"
}

###

POST http://localhost:1337/add-admin/create
Content-Type: application/json

{
    "name": "Pop Adrian",
    "password": "Password#123",
    "invitedBy": "63f4c2720e8a298d3c21be6c",
    "token": "2146d4a9edeb6f13f94196e0d46390ac1fcbea2e91b3d17fbe1472b2fb56d433"
}


# ---------------------------------------------------------------
### ADD NEW ADMIN 
# ---------------------------------------------------------------

POST http://localhost:1337/api/add-admin/request?userId=640606b7719c50752e37dc96
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRyaWFuIiwiZW1haWwiOiJhZHJpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjQwNjA2Yjc3MTljNTA3NTJlMzdkYzk2IiwiaWF0IjoxNjg5MzI3NTY5fQ.FWq_z2su4SA6ooIcdwffjsucgivudHLU_pLRnxuK_RQ

{
    "newAdminEmail": "popadrian@web.de"
}

###

POST http://localhost:1337/api/add-admin/confirm?userId=640606b7719c50752e37dc96
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRyaWFuIiwiZW1haWwiOiJhZHJpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjQwNjA2Yjc3MTljNTA3NTJlMzdkYzk2IiwiaWF0IjoxNjg5MzI3NTY5fQ.FWq_z2su4SA6ooIcdwffjsucgivudHLU_pLRnxuK_RQ

{
    "authCode": "D1C5E5",
    "newAdminEmail": "pa@web.de"
}

###

POST http://localhost:1337/add-admin/create
Content-Type: application/json

{
    "name": "Pop Adrian",
    "password": "Password#123",
    "invitedBy": "63f4c2720e8a298d3c21be6c",
    "token": "2146d4a9edeb6f13f94196e0d46390ac1fcbea2e91b3d17fbe1472b2fb56d433"
}



# ---------------------------------------------------------------
### ADMINS MANAGER
# ---------------------------------------------------------------

GET http://localhost:1337/api/admins-manager/get-list?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjg5MjQxMTY5fQ.WNBDqUO7nJ_dSgDkjgT5UMObJF8CO2j4CzaYf3r62QQ

###

DELETE http://localhost:1337/api/admins-manager/delete-admin/64afb1b8a6089171b842b31c?userId=63f4c2720e8a298d3c21be6c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTHVjaWFuIiwiZW1haWwiOiJsdWNpYW5Ad2ViLmRlIiwidXNlcklkIjoiNjNmNGMyNzIwZThhMjk4ZDNjMjFiZTZjIiwiaWF0IjoxNjg5MjQxMTY5fQ.WNBDqUO7nJ_dSgDkjgT5UMObJF8CO2j4CzaYf3r62QQ

# ---------------------------------------------------------------
### FRONT PAGE DESCRIPTION ** GET // UPDATE
# ---------------------------------------------------------------

GET http://localhost:1337/api/description
Authorization: Bearer xxx

###

POST http://localhost:1337/api/description
Content-Type: application/json
Authorization: Bearer xxx

{
    "description": {
        "title": "Beauty & hair",
        "about": "Comes & first of all"
    }
}

# ---------------------------------------------------------------
### PERSONA ** GET // POST // UPDATE // DELETE
# ---------------------------------------------------------------
