POST http://localhost:1337/users/register
Content-Type: application/json

{
    "credentials": {
        "name": "Lucian",
        "email": "lucian@web.de",
        "password": "pass"
    }
}

###

POST http://localhost:1337/users/login
Content-Type: application/json

{
    "credentials": {
        "email": "adluc@web.de",
        "password": "password"
    }
}

###

GET http://localhost:1337/api/description
Authorization: Bearer xxx

###

POST http://localhost:1337/api/description
Content-Type: application/json
Authorization: Bearer xxx

{
    "description": {
        "title": "Beauty & hair",
        "about": "Comes & first of all"
    }
}

###
POST http://localhost:1337/auth-confirm
Content-Type: application/json

{
    "name": "adrian pop",
    "email": "adluc@web.de",
    "userId": "62a2613db6b4973d1461e78b",
    "authCode": "A3D649"
}

###

PATCH  http://localhost:1337/api/update-credentials/62a2613db6b4973d1461e78b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRyaWFuIHBvcCIsImVtYWlsIjoiYWRsdWNAd2ViLmRlIiwiaWF0IjoxNjU3MTA3NTkyfQ.OFU8pkPk3KPdZ0R0Kbo29-GskKulsE7aQu5WWcs4sdc

{
    "newEmail": "",
    "currentPassword": "Password123#",
    "newPassword": "Password123#"
}